services:
  database:
    container_name: fuel-price-database 
    image: postgres:16.2-alpine3.19
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data 
      - ./docker-data/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Password for the PostgreSQL user, read from .env file
      POSTGRES_USER: ${POSTGRES_USER}  # Username for the PostgreSQL database, read from .env file
      POSTGRES_DB: ${POSTGRES_DB}  # Name of the default database to create, read from .env file
    restart: always  

  # Adminer Database Management Tool
  adminer:
    image: adminer
    restart: always  
    ports:
      - 8080:8080 