services:
  database:
    container_name: fuel-price-database 
    image: postgis/postgis:latest
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data 
      - ./docker-data/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Password for the PostgreSQL user, read from .env file
      POSTGRES_USER: ${POSTGRES_USER}  # Username for the PostgreSQL database, read from .env file
      POSTGRES_DB: ${POSTGRES_DB}  # Name of the default database to create, read from .env file
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5  

  fuel-price:
    container_name: fuel-price-service
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src:delegated
      - ./test:/usr/src/app/test:delegated
      - ./package.json:/usr/src/app/package.json:delegated
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "4000:3000"
    depends_on:
      database:
        condition: service_healthy
    restart: always

  # Adminer Database Management Tool
  adminer:
    image: adminer
    restart: always  
    ports:
      - 8080:8080 